### PR TITLE
style/code fixes

### PR DESCRIPTION
**Pull request by Raskovan**

### CODE REVIEW

**Comment by Raskovan** [comment]
@rcaetano not sure what is happening - Vercel errors out - I have a few fixes, but nothing major... is it supposed to work? Would be great if you can check.

**Comment by rcaetano** [comment]
Wero and I worked on it but we couldn't figure out the issue.  It's the "type conversion error" right?

**Comment by Raskovan** [comment]
> Wero and I worked on it but we couldn't figure out the issue. It's the "type conversion error" right?

`Cannot convert a BigInt value to a number` can you give me access to Vercel, please. Ill take a look

**Comment by Raskovan** [comment]
@rcaetano `const akord_wallet_1 = require("./akord-wallet");` -> `const hdkey_1 = require("ethereum-cryptography/hdkey");` -> `var bip32_1 = require("@scure/bip32");` -> `const POW_2_256 = _2n ** BigInt(256); That's where its coming from...
`

**Comment by Raskovan** [comment]
@rcaetano how is it deployed? I figured, nvm

**Comment by Raskovan** [comment]
@pascaljb should I just deploy it?

**Pull request closed without merging**
